Repository python-discord/site, pull requests merged in 2019-10, with the labels that each got.

#269 Migrate nominations to the new Nomination model
  pydis_site/apps/api/migrations/0044_migrate_nominations_from_infraction_to_nomination_model.py
  pydis_site/apps/api/models/bot/nomination.py
  pydis_site/apps/api/tests/test_models.py
Labels: API, Backend, critical

#281 Allow viewing log entries in the Django Admin.
  pydis_site/apps/api/admin.py
  pydis_site/apps/api/migrations/0045_add_plural_name_for_log_entry.py
  pydis_site/apps/api/models/log_entry.py
  pydis_site/apps/api/tests/test_models.py
Labels: Backend, Frontend, python

#274 Django Allauth (#201)
  Pipfile
  Pipfile.lock
  pydis_site/apps/home/__init__.py
  pydis_site/apps/home/apps.py
  pydis_site/apps/home/signals.py
  pydis_site/apps/home/tests/test_signal_listener.py
  pydis_site/apps/home/tests/test_views.py
  pydis_site/apps/home/urls.py
  pydis_site/apps/staff/admin.py
  pydis_site/apps/staff/migrations/0001_initial.py
  pydis_site/apps/staff/models/__init__.py
  pydis_site/apps/staff/models/role_mapping.py
  pydis_site/settings.py
  pydis_site/static/css/base/base.css
  pydis_site/static/css/base/notification.css
  pydis_site/static/css/wiki/simplemde.min.css
  pydis_site/static/js/wiki/simplemde.min.js
  pydis_site/templates/base/base.html
  pydis_site/templates/base/navbar.html
  pydis_site/templates/wiki/base.html
  pydis_site/utils/views.py
Labels: Backend, Frontend, enhancement, python

#285 Wiki: Permissions hotfix
  pydis_site/settings.py
Labels: Backend, critical, enhancement, python

#286 Wiki polish (RE: Allauth)
  pydis_site/templates/wiki/base.html
  pydis_site/templates/wiki/includes/breadcrumbs.html
  pydis_site/templates/wiki/includes/messages.html
Labels: Frontend, bug, enhancement
