Repository python-discord/site, pull requests merged in 2020-12, with the labels that each got.

#431 Set max-requests-jitter parameter to gunicorn
  manage.py
Labels: area: CI, area: backend, priority: 0 - critical

#435 Hotfix: Add some sanity to frontpage projects.
  pydis_site/apps/home/tests/test_repodata_helpers.py
  pydis_site/apps/home/views/home.py
  pydis_site/templates/home/index.html
Labels: needs 1 approval

#437 Increase per_page to 100 for GitHub API call.
  pydis_site/apps/home/views/home.py
Labels: needs 2 approvals

#432 Include DestroyModelMixin to infractions view for DELETE method
  pydis_site/apps/api/tests/test_infractions.py
  pydis_site/apps/api/viewsets/bot/infraction.py
Labels: area: API, priority: 2 - normal, type: feature

#438 Swap Metricity verified_at for joined_at
  postgres/init.sql
  pydis_site/apps/api/models/bot/metricity.py
  pydis_site/apps/api/tests/test_users.py
  pydis_site/apps/api/viewsets/bot/user.py
Labels: needs 2 approvals

#439 Sentry SDK version bump, Git SHA simplification
  .dockerignore
  .github/workflows/build.yaml
  .github/workflows/sentry-release.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  pydis_site/constants.py
  pydis_site/settings.py
Labels: area: CI, area: dependencies, needs 1 approval
