Repository python-discord/site, pull requests merged in 2020-03, with the labels that each got.

#337 Install wiki from PyPI
  Pipfile
  Pipfile.lock
  docker/wheels/wiki-0.5.dev20190420204942-py3-none-any.whl
Labels: area: dependencies, priority: 2 - normal, status: needs review, type: feature

#304 Make newlines visible in deleted messages
  pydis_site/apps/staff/templatetags/deletedmessage_filters.py
  pydis_site/apps/staff/tests/test_deletedmessage_filters.py
  pydis_site/static/css/staff/logs.css
  pydis_site/templates/staff/logs.html
Labels: area: frontend, type: feature

#339 Add more pre-commit hooks
  .flake8
  .gitattributes
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Pipfile
  Pipfile.lock
  azure-pipelines.yml
  pydis_site/apps/api/tests/base.py
  pydis_site/apps/api/tests/test_deleted_messages.py
  pydis_site/apps/api/tests/test_documentation_links.py
  pydis_site/apps/api/tests/test_infractions.py
  pydis_site/apps/api/tests/test_nominations.py
  pydis_site/apps/api/tests/test_off_topic_channel_names.py
  pydis_site/apps/api/tests/test_offensive_message.py
  pydis_site/apps/api/tests/test_roles.py
  pydis_site/apps/api/tests/test_users.py
  pydis_site/apps/api/views.py
  pydis_site/apps/home/tests/test_repodata_helpers.py
  pydis_site/static/css/home/index.css
  pydis_site/static/favicons/safari-pinned-tab.svg
  pydis_site/templates/home/account/settings.html
  pydis_site/templates/home/index.html
  pydis_site/templates/wiki/history.html
Labels: area: CI, area: dependencies, priority: 2 - normal, status: needs review, type: feature

#343 Update contributor doc
  CONTRIBUTING.md
Labels: area: docs, type: feature
