Repository python-discord/site, pull requests merged in 2020-11, with the labels that each got.

#423 Migrate to GH Actions & GH Container Registry
  .flake8
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint-test-build.yaml
  Pipfile
  Pipfile.lock
  azure-pipelines.yml
Labels: area: CI, priority: 0 - critical

#424 Kubernetes deployment
  .github/workflows/lint-test-deploy.yaml
  README.md
  deployment.yaml
Labels: needs 1 approval

#425 Ensure that flake8 runs correctly in the CI
  .github/workflows/build-deploy.yaml
  .github/workflows/lint-test.yaml
  README.md
Labels: area: CI, priority: 0 - critical

#426 Restructure Build & Deploy sequence in CI
  .github/workflows/build.yaml
  .github/workflows/deploy.yaml
  deployment.yaml
Labels: area: CI, status: stalled
