Repository python-discord/site, pull requests merged in 2021-03, with the labels that each got.

#450 New error pages
  pydis_site/static/css/error_pages.css
  pydis_site/templates/404.html
  pydis_site/templates/500.html
Labels: area: frontend, priority: 2 - normal, type: feature

#447 Rework nominations
  pydis_site/apps/api/admin.py
  pydis_site/apps/api/migrations/0068_split_nomination_tables.py
  pydis_site/apps/api/models/__init__.py
  pydis_site/apps/api/models/bot/__init__.py
  pydis_site/apps/api/models/bot/nomination.py
  pydis_site/apps/api/serializers.py
  pydis_site/apps/api/tests/test_models.py
  pydis_site/apps/api/tests/test_nominations.py
  pydis_site/apps/api/viewsets/bot/nomination.py
Labels: area: API, priority: 1 - high

#451 Add route to get a member's data for helper review
  postgres/init.sql
  pydis_site/apps/api/models/bot/metricity.py
  pydis_site/apps/api/tests/test_users.py
  pydis_site/apps/api/viewsets/bot/user.py
Labels: area: API, language: python, type: feature

#460 Adds Streamyard Banner To Homepage
  pydis_site/static/css/home/index.css
  pydis_site/static/images/sponsors/streamyard.png
  pydis_site/templates/home/index.html
Labels: area: frontend, priority: 2 - normal, type: feature

#461 Removes Gunicorn Import In Debug Mode
  manage.py
Labels: area: dependencies, type: bug
