Repository python-discord/site, pull requests merged in 2021-05, with the labels that each got.

#485 Dewikification - Implement redirections app
  docs/README.md
  pydis_site/apps/content/resources/privacy.md
  pydis_site/apps/home/urls.py
  pydis_site/apps/redirect/__init__.py
  pydis_site/apps/redirect/apps.py
  pydis_site/apps/redirect/migrations/__init__.py
  pydis_site/apps/redirect/redirects.yaml
  pydis_site/apps/redirect/tests.py
  pydis_site/apps/redirect/urls.py
  pydis_site/apps/redirect/views.py
  pydis_site/settings.py
  pydis_site/templates/base/navbar.html
Labels: project: dewikification

#491 Change rules to those agreed upon in prior staff meeting.
  pydis_site/apps/content/resources/rules.md
Labels: area: admin

#495 Reorganizes Contributing Guidelines
  pydis_site/apps/content/resources/guides/pydis-guides/contributing.md
  pydis_site/apps/content/resources/guides/pydis-guides/contributing/contributing-guidelines.md
  pydis_site/apps/content/resources/guides/pydis-guides/contributing/contributing-guidelines/supplemental-information.md
Labels: area: docs, type: feature
