Repository python-discord/site, pull requests merged in 2021-07, with the labels that each got.

#551 CJ8 Information Update
  pydis_site/templates/events/pages/code-jams/8/_index.html
  pydis_site/templates/events/pages/code-jams/8/frameworks.html
Labels: area: frontend

#550 Create The Code Style Guide
  pydis_site/templates/events/pages/code-jams/code-style-guide.html
  pydis_site/templates/events/sidebar/code-jams/8.html
  pydis_site/templates/events/sidebar/code-jams/useful-information.html
Labels: area: frontend, priority: 1 - high

#557 Documents expected emoji format in env vars
  pydis_site/apps/content/resources/guides/pydis-guides/contributing/sir-lancebot/env-var-reference.md
Labels: area: docs, type: feature

#556 Fixes Broken Doc Link
  pydis_site/apps/content/resources/guides/pydis-guides/contributing/sir-lancebot.md
Labels: area: docs, level: 0 - beginner, type: bug

#553 Improvements & fixes to homepage repository display.
  pydis_site/apps/home/views/home.py
Labels: area: backend, language: python
