Repository python-discord/site, pull requests merged in 2021-06, with the labels that each got.

#510 Add new infraction filters for the infraction rescheduler
  pydis_site/apps/api/tests/test_infractions.py
  pydis_site/apps/api/viewsets/bot/infraction.py
Labels: area: API, language: python, priority: 0 - critical, python, type: feature

#518 Update `IntegrityError` pattern for PostgreSQL 13.
  pydis_site/apps/api/tests/test_infractions.py
Labels: area: tests

#520 Include metricity db creation for local setup guide.
  pydis_site/apps/content/resources/guides/pydis-guides/contributing/site.md
Labels: area: docs

#519 Fix `content` app tests not running on macOS.
  pydis_site/apps/content/tests/helpers.py
  pydis_site/apps/content/tests/test_utils.py
  pydis_site/apps/content/tests/test_views.py
Labels: area: tests

#528 Code Jam 8 - Initial PR for Announcement
  pydis_site/static/images/events/cj8_asciimatics.png
  pydis_site/static/images/events/cj8_blessed.gif
  pydis_site/static/images/events/cj8_curses.png
  pydis_site/static/images/events/cj8_rich.gif
  pydis_site/static/images/events/cj8_urwid.png
  pydis_site/static/images/events/summer_code_jam_2021.png
  pydis_site/templates/events/index.html
  pydis_site/templates/events/pages/code-jams/8/_index.html
  pydis_site/templates/events/pages/code-jams/8/frameworks.html
  pydis_site/templates/events/pages/code-jams/8/rules.html
  pydis_site/templates/events/sidebar/code-jams/8.html
  pydis_site/templates/events/sidebar/code-jams/previous-code-jams.html
  pydis_site/templates/events/sidebar/code-jams/upcoming-code-jam.html
  pydis_site/templates/events/sidebar/upcoming-event.html
Labels: area: frontend, priority: 1 - high

#529 Minor amendments to Code Jam 8 docs
  pydis_site/templates/events/pages/code-jams/8/_index.html
Labels: area: frontend, level: 2 - advanced, priority: 0 - critical, type: bug

#530 Code Jam 8 Site Updates - v2
  pydis_site/static/images/events/DO_Logo_Vertical_Blue.png
  pydis_site/templates/base/navbar.html
  pydis_site/templates/events/pages/code-jams/8/_index.html
  pydis_site/templates/events/pages/code-jams/8/frameworks.html
  pydis_site/templates/events/pages/code-jams/8/rules.html
  pydis_site/templates/events/sidebar/code-jams/8.html
Labels: area: frontend, priority: 1 - high

#532 Approve more frameworks for CJ8
  pydis_site/static/images/events/cj8_prompttoolkit.png
  pydis_site/templates/events/pages/code-jams/8/frameworks.html
Labels: area: frontend, priority: 1 - high

#541 Code Jam 8 - Qualifier Release Update
  pydis_site/static/images/events/Tabnine.png
  pydis_site/templates/events/pages/code-jams/8/_index.html
  pydis_site/templates/events/pages/code-jams/8/github-bootcamp.html
  pydis_site/templates/events/sidebar/code-jams/8.html
Labels: area: frontend, priority: 0 - critical

#543 Updating bootcamp information
  pydis_site/templates/events/pages/code-jams/8/_index.html
  pydis_site/templates/events/pages/code-jams/8/github-bootcamp.html
Labels: area: frontend, priority: 1 - high

#536 Adjust Message model to support new nitro messages with over 4000 chars
  pydis_site/apps/api/migrations/0071_increase_message_content_4000.py
  pydis_site/apps/api/models/bot/message.py
  pydis_site/apps/api/tests/test_models.py
Labels: area: API, priority: 0 - critical, type: bug

#523 Move config docs to contributing guide, kill `docs` directory.
  docs/README.md
  docs/configuration.md
  docs/setup.md
  pydis_site/apps/content/resources/guides/pydis-guides/contributing/site.md
Labels: area: docs
