Repository python-discord/site, pull requests merged in 2021-04, with the labels that each got.

#468 Dewikification: Content app improvements.
  pydis_site/apps/content/resources/_info.yml
  pydis_site/apps/content/resources/guides/_info.yml
  pydis_site/apps/content/resources/guides/pydis-guides/_info.yml
  pydis_site/apps/content/resources/guides/pydis-guides/how-to-contribute-a-page.md
  pydis_site/apps/content/tests/helpers.py
  pydis_site/apps/content/tests/test_utils.py
  pydis_site/apps/content/tests/test_views.py
  pydis_site/apps/content/utils.py
  pydis_site/apps/content/views/page_category.py
  pydis_site/apps/events/tests/test_views.py
  pydis_site/apps/events/views/page.py
  pydis_site/settings.py
  pydis_site/static/css/content/page.css
  pydis_site/templates/content/base.html
  pydis_site/templates/content/dropdown.html
  pydis_site/templates/content/listing.html
  pydis_site/templates/content/page.html
Labels: priority: 1 - high, type: feature

#472 Migrate GHCR_TOKEN -> GITHUB_TOKEN in Docker build action
  .github/workflows/build.yaml
Labels: area: CI

#373 Add a validator for documentation package names and base urls.
  pydis_site/apps/api/migrations/0069_documentationlink_validators.py
  pydis_site/apps/api/models/bot/documentation_link.py
  pydis_site/apps/api/tests/test_documentation_links.py
Labels: area: API, s: waiting for author, type: feature
