Repository python-discord/site, pull requests merged in 2021-09, with the labels that each got.

#575 Add Django Prometheus
  .flake8
  Dockerfile
  gunicorn.conf.py
  manage.py
  poetry.lock
  pydis_site/apps/home/urls.py
  pydis_site/settings.py
  pyproject.toml
Labels: area: backend, type: feature, priority: 1 - high, review: needs devops

#583 Initialise metricity at runtime
  docker-compose.yml
  manage.py
  postgres/init.sql
Labels: area: backend, priority: 1 - high, area: CI

#589 Update repository selection on home page
  pydis_site/apps/home/tests/mock_github_api_response.json
  pydis_site/apps/home/views/home.py
Labels: area: frontend, language: python, priority: 2 - normal

#590 Code Jam Wrap Up
  pydis_site/templates/events/index.html
  pydis_site/templates/events/pages/code-jams/8/_index.html
  pydis_site/templates/events/pages/code-jams/_index.html
  pydis_site/templates/events/sidebar/code-jams/previous-code-jams.html
  pydis_site/templates/events/sidebar/events-list.html
  pydis_site/templates/home/index.html
Labels: area: frontend
