Repository python-discord/site, pull requests merged in 2022-01, with the labels that each got.

#645 Prevent page title from overlapping dropdown button.
  pydis_site/templates/content/dropdown.html
Labels: type: bug, area: frontend

#608 Implement voice mute and migration from voice ban -> voice mute
  pydis_site/apps/api/migrations/0074_voice_mute.py
  pydis_site/apps/api/migrations/0079_merge_20220125_2022.py
  pydis_site/apps/api/models/bot/infraction.py
  pydis_site/apps/api/serializers.py
Labels: hacktoberfest-accepted

#646 Fix pynews config in example file
  pydis_site/apps/content/resources/guides/pydis-guides/contributing/bot.md
Labels: area: docs, priority: 2 - normal, s: needs review

#647 Use voice_mute and voice_ban to determine voice_gate
  pydis_site/apps/api/tests/test_users.py
  pydis_site/apps/api/viewsets/bot/user.py
Labels: type: bug, priority: 0 - critical, area: API, s: needs review
