Repository python-discord/site, pull requests merged in 2022-11, with the labels that each got.

#763 List Bot Tags On Site
  poetry.lock
  pydis_site/apps/api/github_utils.py
  pydis_site/apps/api/tests/test_github_utils.py
  pydis_site/apps/content/migrations/0001_add_tags.py
  pydis_site/apps/content/migrations/__init__.py
  pydis_site/apps/content/models/__init__.py
  pydis_site/apps/content/models/tag.py
  pydis_site/apps/content/resources/tags/_info.yml
  pydis_site/apps/content/tests/test_utils.py
  pydis_site/apps/content/tests/test_views.py
  pydis_site/apps/content/urls.py
  pydis_site/apps/content/utils.py
  pydis_site/apps/content/views/__init__.py
  pydis_site/apps/content/views/page_category.py
  pydis_site/apps/content/views/tags.py
  pydis_site/apps/home/views/home.py
  pydis_site/apps/redirect/urls.py
  pydis_site/settings.py
  pydis_site/static/css/content/color.css
  pydis_site/static/css/content/tag.css
  pydis_site/static/js/content/listing.js
  pydis_site/templates/base/navbar.html
  pydis_site/templates/content/base.html
  pydis_site/templates/content/listing.html
  pydis_site/templates/content/page.html
  pydis_site/templates/content/tag.html
  pydis_site/urls.py
  pyproject.toml
Labels: area: frontend, type: feature, priority: 2 - normal, s: needs review

#796 Migration of SSL verification error pin
  pydis_site/apps/content/resources/guides/python-guides/fix-ssl-certificate.md
  pydis_site/static/images/content/fix-ssl-certificate/pem.png
Labels: area: frontend, priority: 2 - normal, type: enhancement, s: needs review

#789 Messages in past n days endpoint
  pydis_site/apps/api/models/bot/metricity.py
  pydis_site/apps/api/tests/test_users.py
  pydis_site/apps/api/viewsets/bot/user.py
Labels: area: API, type: feature, priority: 2 - normal, python, s: needs review

#701 Migrate "Keeping Discord Bot Tokens Safe" pin
  pydis_site/apps/content/resources/guides/python-guides/keeping-tokens-safe.md
  pydis_site/static/images/content/regenerating_token.jpg
Labels: area: frontend, type: feature, priority: 2 - normal

#765 Migrate on_command_error pin
  pydis_site/apps/content/resources/guides/python-guides/proper-error-handling.md
Labels: area: frontend, type: feature, priority: 2 - normal, s: needs review
