Repository python-discord/site, pull requests merged in 2022-04, with the labels that each got.

#690 Added Discord embed limits guide
  pydis_site/apps/content/resources/guides/python-guides/discord-embed-limits.md
Labels: area: frontend, type: feature, priority: 2 - normal, s: waiting for author

#716 Support color string being when converting to hex code
  pydis_site/apps/staff/templatetags/deletedmessage_filters.py
  pydis_site/apps/staff/tests/test_logs_view.py
Labels: area: frontend, priority: 1 - high, s: needs review

#718 Invert Deleted Message Log Order
  pydis_site/templates/staff/logs.html
Labels: area: frontend, priority: 2 - normal, area: moderation, type: enhancement

#698 Add custom help command
  pydis_site/apps/content/resources/guides/python-guides/discordpy_help_command.md
Labels: area: frontend, type: feature, priority: 2 - normal, s: needs review

#700 Don't do JSON as a database, kids.
  pydis_site/apps/content/resources/guides/python-guides/why-not-json-as-database.md
Labels: area: frontend, type: feature, priority: 2 - normal, s: needs review

#691 Added Discord messages with colors guide
  pydis_site/apps/content/resources/guides/python-guides/discord-messages-with-colors.md
  pydis_site/static/images/content/discord_colored_messages/ansi-colors.png
  pydis_site/static/images/content/discord_colored_messages/result.png
Labels: area: frontend, type: feature, priority: 2 - normal
