Repository python-discord/site, pull requests merged in 2022-03, with the labels that each got.

#684 Remove test warnings & logline, prevent introducing them again in the future
  pydis_site/apps/api/tests/test_infractions.py
  pydis_site/apps/api/tests/test_models.py
  pydis_site/apps/api/tests/test_reminders.py
  pydis_site/apps/api/viewsets/bot/infraction.py
  pydis_site/apps/home/tests/test_repodata_helpers.py
  pydis_site/settings.py
Labels: area: backend, area: tests, priority: 2 - normal, level: 2 - advanced, python, type: enhancement

#686 Add a README for the API app
  pydis_site/apps/api/README.md
Labels: area: docs

#693 Add a README for the content directory
  pydis_site/apps/content/README.md
  pydis_site/apps/content/migrations/__init__.py
Labels: area: docs, level: 1 - intermediate

#694 Update roles page
  pydis_site/apps/content/resources/server-info/roles.md
Labels: area: frontend, type: enhancement

#663 Add support for BumpedThreads to be stored in site
  pydis_site/apps/api/migrations/0081_bumpedthread.py
  pydis_site/apps/api/models/__init__.py
  pydis_site/apps/api/models/bot/__init__.py
  pydis_site/apps/api/models/bot/bumped_thread.py
  pydis_site/apps/api/serializers.py
  pydis_site/apps/api/tests/test_bumped_threads.py
  pydis_site/apps/api/urls.py
  pydis_site/apps/api/viewsets/__init__.py
  pydis_site/apps/api/viewsets/bot/__init__.py
  pydis_site/apps/api/viewsets/bot/bumped_thread.py
Labels: area: API, language: python, type: feature, priority: 2 - normal, s: needs review

#705 Fix link to code jam image
  pydis_site/templates/events/sidebar/code-jams/7.html
Labels: area: backend, priority: 2 - normal, type: enhancement, s: needs review
