Repository python-discord/site, pull requests merged in 2022-12, with the labels that each got.

#746 Created a guide on how to run a bot with Docker and setup GitHub Actions for CI
  pydis_site/apps/content/resources/guides/python-guides/docker-hosting-guide.md
Labels: area: frontend, type: feature, priority: 2 - normal, s: waiting for author

#733 Added discord-app-commands.md
  pydis_site/apps/content/resources/guides/python-guides/app-commands.md
Labels: area: frontend, type: feature, priority: 2 - normal

#709 Migrate Setting Different Statuses to Set Your Bot Pin by Python Bot
  pydis_site/apps/content/resources/guides/python-guides/setting-different-statuses-on-your-bot.md
Labels: area: frontend, type: feature, priority: 2 - normal

#814 Update help channels guide
  pydis_site/apps/content/resources/guides/pydis-guides/help-channel-guide.md
  pydis_site/apps/content/resources/guides/pydis-guides/helping-others.md
  pydis_site/static/images/content/help_channels/available_channels.png
  pydis_site/static/images/content/help_channels/available_message.png
  pydis_site/static/images/content/help_channels/claimed_channel.png
  pydis_site/static/images/content/help_channels/dormant_channels.png
  pydis_site/static/images/content/help_channels/help-system-category.png
  pydis_site/static/images/content/help_channels/new-post-button.png
  pydis_site/static/images/content/help_channels/new-post-form.png
  pydis_site/static/images/content/help_channels/newly-created-thread-example.png
  pydis_site/static/images/content/help_channels/occupied_channels.png
  pydis_site/static/images/content/help_channels/question-example.png
Labels: area: frontend, s: needs review
