Repository python-discord/site, pull requests merged in 2022-08, with the labels that each got.

#741 Remove IP Specification From Compose Ports
  .github/workflows/lint-test.yaml
  docker-compose.yml
  manage.py
  pyproject.toml
Labels: area: tests, type: enhancement

#758 Added `last_applied` to `serializers`
  pydis_site/apps/api/serializers.py
Labels: type: bug, area: API, s: needs review

#742 Add GitHub Artifacts API Route
  .gitignore
  poetry.lock
  pydis_site/apps/api/github_utils.py
  pydis_site/apps/api/tests/test_github_utils.py
  pydis_site/apps/api/urls.py
  pydis_site/apps/api/views.py
  pydis_site/settings.py
  pyproject.toml
  static-builds/README.md
  static-builds/netlify_build.py
Labels: type: bug, area: backend, priority: 2 - normal

#762 Static Builds Small Improvements
  pydis_site/apps/api/github_utils.py
  static-builds/netlify_build.py
Labels: type: bug, priority: 3 - low, area: CI

#764 Explicitly Specify Infraction Time In Tests
  pydis_site/apps/api/tests/test_infractions.py
Labels: type: bug, area: tests, priority: 1 - high
