Repository python-discord/site, pull requests merged in 2023-02, with the labels that each got.

#874 Remove admonition from /events/ that says CJ9 is underway
  pydis_site/templates/events/index.html
Labels: area: frontend, s: needs review

#879 Reverse timeline entries so newest entries come first
  pydis_site/templates/home/timeline.html
Labels: area: frontend, priority: 2 - normal, type: enhancement, s: needs review

#847 Utilise Poetry groups
  .github/workflows/lint-test.yaml
  Dockerfile
  poetry.lock
  pyproject.toml
Labels: area: dependencies, type: enhancement, s: needs review
