Repository python-discord/site, pull requests merged in 2024-01, with the labels that each got.

#1194 Add 'Software Design by Example' to resources. (fix #1193)
  pydis_site/apps/resources/resources/software_design_by_example.yaml
Labels: area: frontend, type: feature, priority: 2 - normal

#1138 Fixed truncated dropdown menu
  pydis_site/static/css/content/page.css
Labels: area: frontend, priority: 2 - normal, type: enhancement, s: needs review

#1215 Add section about working with dark mode in the guide on contributing a page
  pydis_site/apps/content/resources/guides/pydis-guides/how-to-contribute-a-page.md
Labels: area: docs, priority: 3 - low, type: enhancement, s: needs review
