Repository python-discord/site, pull requests merged in 2024-03, with the labels that each got.

#1232 Move from Font Awesome Kit to serving our own FA static files
  pydis_site/settings.py
  pydis_site/static/fontawesome/LICENSE.txt
  pydis_site/static/fontawesome/README.md
  pydis_site/static/fontawesome/UPGRADING.md
  pydis_site/static/fontawesome/css/all.min.css
  pydis_site/static/fontawesome/webfonts/fa-brands-400.ttf
  pydis_site/static/fontawesome/webfonts/fa-brands-400.woff2
  pydis_site/static/fontawesome/webfonts/fa-regular-400.ttf
  pydis_site/static/fontawesome/webfonts/fa-regular-400.woff2
  pydis_site/static/fontawesome/webfonts/fa-solid-900.ttf
  pydis_site/static/fontawesome/webfonts/fa-solid-900.woff2
  pydis_site/static/fontawesome/webfonts/fa-v4compatibility.ttf
  pydis_site/static/fontawesome/webfonts/fa-v4compatibility.woff2
  pydis_site/templates/base/base.html
Labels: area: dependencies, area: frontend, s: needs review

#1226 Document how to add new resources
  pydis_site/apps/resources/README.md
  pydis_site/templates/resources/resources.html
Labels: area: docs, s: needs review

#1231 Add docs for development on Bulma, CSS, and dark mode colors
  pydis_site/README.md
  pydis_site/settings.py
  pydis_site/static/css/README.md
  pydis_site/static/images/README.md
Labels: area: docs, area: frontend, s: needs review

#1255 Fix legacy Font Awesome icon classes
  pydis_site/apps/resources/templatetags/get_category_icon.py
  pydis_site/templates/events/pages/code-jams/10/_index.html
  pydis_site/templates/events/pages/code-jams/8/_index.html
  pydis_site/templates/events/pages/code-jams/9/_index.html
  pydis_site/templates/home/timeline.html
Labels: area: frontend, priority: 2 - normal, type: enhancement, s: needs review

#1261 Timeline: Fix Liechtenstein postcard image
  pydis_site/templates/home/timeline.html
Labels: area: frontend, s: needs review

#1270 Removed inactive users from `CODEOWNERS`
  .github/CODEOWNERS
Labels: priority: 3 - low, type: enhancement, s: needs review

#1266 Fix broken Bulma logo in the footer
  pydis_site/static/css/base/base.css
Labels: type: bug, area: frontend, s: needs review

#1268 Use proper logos and better positioning in the footers
  pydis_site/static/css/base/base.css
  pydis_site/static/images/sponsors_dark/linode_text.png
Labels: area: frontend, s: needs review

#1210 Redesign of events page
  pydis_site/apps/events/README.md
  pydis_site/settings.py
  pydis_site/static/css/events/base.css
  pydis_site/static/images/events/gallery/adventofcode.png
  pydis_site/static/images/events/gallery/pixels.png
  pydis_site/static/images/events/gallery/pyweek.png
  pydis_site/static/images/events/gallery/pyweek_dark.png
  pydis_site/static/images/events/icons/adventofcode.png
  pydis_site/static/images/events/icons/codejam.svg
  pydis_site/static/images/events/icons/pixels.png
  pydis_site/static/images/events/icons/pyweek.png
  pydis_site/static/images/events/pixels_logo_transparent.gif
  pydis_site/static/images/events/pixels_logo_transparent.png
  pydis_site/static/images/events/summer_code_jam_2023/banner2.png
  pydis_site/static/images/events/summer_code_jam_2023/banner3.png
  pydis_site/static/images/events/summer_code_jam_2023/logo.PNG
  pydis_site/templates/events/README.md
  pydis_site/templates/events/current_event.html
  pydis_site/templates/events/index.html
  pydis_site/templates/events/main_events.html
  pydis_site/templates/events/other_events.html
  pydis_site/templates/events/pages/adventofcode/_index.html
  pydis_site/templates/events/pages/game-jams/_index.html
  pydis_site/templates/events/pages/pixels/_index.html
  pydis_site/templates/events/pages/pyweek/_index.html
  pydis_site/templates/events/pages/revivalofcode/_index.html
  pydis_site/templates/events/scheduled_events.html
  pydis_site/templates/events/sidebar/adventofcode/useful-links.html
  pydis_site/templates/events/sidebar/code-jams/10.html
  pydis_site/templates/events/sidebar/code-jams/ongoing-code-jam.html
  pydis_site/templates/events/sidebar/events-list.html
  pydis_site/templates/events/sidebar/main_sidebar.html
  pydis_site/templates/events/sidebar/ongoing-event.html
  pydis_site/templates/events/sidebar/pixels.html
  pydis_site/templates/events/sidebar/pyweek/useful-links.html
  pydis_site/templates/events/sidebar/revivalofcode.html
  pydis_site/templates/home/index.html
Labels: area: frontend, priority: 2 - normal, type: enhancement, s: needs review

#1273 Fix navbar dropdown toggle for touchscreens using Safari
  pydis_site/templates/base/base.html
Labels: type: bug, area: frontend, s: needs review

#1262 Timeline CSS refactor
  pydis_site/static/css/home/timeline.css
  pydis_site/static/images/timeline/cd-icon-pydis.svg
  pydis_site/static/js/timeline/main.js
  pydis_site/templates/home/timeline.html
Labels: area: frontend, type: enhancement, s: needs review

#1276 Support running tests with --keepdb option
  pydis_site/apps/api/tests/test_deleted_messages.py
  pydis_site/apps/api/tests/test_reminders.py
Labels: area: tests, priority: 3 - low, level: 0 - beginner, type: enhancement
